import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Number from '../components/number'
import Operator from '../components/operator'
import Action from '../components/action'
import Display from '../components/display'
import React, { useEffect, useState } from 'react'

export default function Home() {
  let [expression, setExpression] = useState('0')

  const clearDisplay = () => {
    setExpression('0')
  }

  const convertToNegative = () => {
    if (expression [0] === '-') {
      setExpression(expression.slice(1))
    } else {
      setExpression('-' + expression)
    }
  }

  const addToExpression = (e) => {
    if (expression === '0') {
      setExpression(e.target.innerText)
    }else{
      setExpression(expression + e.target.innerText)
    }
    
  }

  const calculate = () => {
    setExpression(eval(expression))
    console.log(expression.length)
    if(expression.length > 10){
      setExpression('Error')
    }

  }

  const calculatePercent = () => {
    setExpression(eval(eval(expression) / 100))
  }




  return (
    <div className={styles.container}>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Display expression={expression}/>

      <main className={styles.main}>
        <Action value="AC" onClick={clearDisplay}/>                
        <Action value="neg" onClick={convertToNegative}/>                
        <Action value="%" onClick={calculatePercent}/>        
        <Operator value="/" operator="/" onClick={addToExpression}/>
        <Number value="7" onClick={addToExpression}/>
        <Number value="8" onClick={addToExpression}/>
        <Number value="9" onClick={addToExpression}/>        
        <Operator value="*" operator="." onClick={addToExpression}/>
        <Number value="4" onClick={addToExpression}/>
        <Number value="5" onClick={addToExpression}/>
        <Number value="6" onClick={addToExpression}/>
        <Operator value="-" onClick={addToExpression}/>
        <Number value="1" onClick={addToExpression}/>
        <Number value="2" onClick={addToExpression}/>
        <Number value="3" onClick={addToExpression}/>
        <Operator value="+" operator="+" onClick={addToExpression}/>
        <Number value="0" zero="true" onClick={addToExpression}/>
        <Number value="," onClick={addToExpression}/>
        <Operator value="=" operator="=" onClick={calculate}/>
      </main>

      
    </div>
  )
}
