import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Number from '../components/number'
import Operator from '../components/operator'
import Action from '../components/action'
import Display from '../components/display'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Display/>

      <main className={styles.main}>
        <Action ac="AC"/>                
        <Action ac="neg"/>                
        <Action ac="%"/>        
        <Operator op="÷"/>
        <Number number="7"/>
        <Number number="8"/>
        <Number number="9"/>        
        <Operator op="x"/>
        <Number number="4" />
        <Number number="5" />
        <Number number="6" />
        <Operator op="-"/>
        <Number number="1" />
        <Number number="2" />
        <Number number="3" />
        <Operator op="+"/>
        <Number number="0" zero="true"s/>
        <Number number="." />
        <Operator op="="/>
      </main>

      
    </div>
  )
}
