import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
import Number from '../components/number'
import Operator from '../components/operator'
import Action from '../components/action'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Action/>                
        <Action/>                
        <Action/>        
        <Operator />
        <Number number="7"/>
        <Number number="8"/>
        <Number number="9"/>        
        <Operator/>
        <Number number="4" />
        <Number number="5" />
        <Number number="6" />
        <Operator/>
        <Number number="1" />
        <Number number="2" />
        <Number number="3" />
        <Operator/>
        <Number number="0" zero="true"/>
        <Number number="." />
        <Operator />
      </main>

      
    </div>
  )
}
